### PR TITLE
remove broken links from javascript and ror docs

### PR DESCRIPTION
**Pull request by kanagarajkm**
Links to javascript-shopping-app and ror-resume-uploader-app
docs are removed.

### CODE REVIEW

**Comment by kannappanr** [comment]
If `https://github.com/minio/minio-js-store-app` is the github link, can we not point that, instead of removing it

**Comment by kanagarajkm** [comment]
> If `https://github.com/minio/minio-js-store-app` is the github link, can we not point that, instead of removing it

yes, will do

**Comment by kanagarajkm** [comment]
@kannappanr done, please have a look

**Comment by kanagarajkm** [comment]
@ebozduman done, please have a look

**Pull request merged**
