### PR TITLE
docs: added reference to use generic http/https profile in mountainduck.

### PR DESCRIPTION
**Pull request by koolhead17**

### CODE REVIEW

**Comment by koolhead17** [comment]
This PR will close https://github.com/minio/cookbook/issues/113#event-893234241

**Comment by deekoder** [comment]
Cyberduck is in MountainDuck. Please fix.

**Comment by koolhead17** [comment]
@deekoder My bad. I should have also added a note that i have formatted structuring of cyberduck doc as well along with this patch.

Let me clarify:

* This patch adds reference of  generic S3 ``HTTP`` profile in mountainduck cookbook.
* This patch also does sentence restructuring related to generic S3 ``HTTP`` profile in cyberduck doc.

**Comment by deekoder** [comment]
ok. Accepting this PR.

**Pull request merged**
